services:
  - type: web
    name: transcriptor-audio
    env: python
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn app:app -c gunicorn_config.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
    publishDir: .  # Agregar esta línea para especificar el directorio raíz
    autoDeploy: true
