services:
  - type: web
    name: transcriptor-audio
    env: python
    plan: free
    buildCommand: bash build.sh
    startCommand: gunicorn app:app -c gunicorn_config.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
    autoDeploy: true
